FROM node:18-alpine

RUN mkdir -p /usr/src/app/dev

WORKDIR /usr/src/app

RUN npm install -g nodemon

COPY package*.json .

RUN npm install && npm cache clean --force

COPY . ./dev

EXPOSE 3000

CMD [ "nodemon", "./dev/index.js" ]